name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - main
trigger:
  branches:
    include:
      - main

jobs:
  - job: build_and_deploy_job
    displayName: Build and Deploy Job
    condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
    pool:
      vmImage: ubuntu-latest
    variables:
      - group: Azure-Static-Web-Apps-jolly-flower-049f9721e-variable-group
    steps:
      - checkout: self
        submodules: true
      - task: AzureStaticWebApp@0
        inputs:
          azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_FLOWER_049F9721E)
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
      - script: |
          echo "Building the Next.js app with environment variables"
          npm install
          npm run build
        env:
          NEXT_PUBLIC_RECAPTCHA_SITE_KEY: $(NEXT_PUBLIC_RECAPTCHA_SITE_KEY)
          NEXT_PUBLIC_FULFILL3D_API_ENDPOINT: $(NEXT_PUBLIC_FULFILL3D_API_ENDPOINT)
          NEXT_PUBLIC_SEND_FORM_REQUEST_ENDPOINT: $(NEXT_PUBLIC_SEND_FORM_REQUEST_ENDPOINT)
